version: 2

# Adapted from https://github.com/circleci/circleci-docs/blob/master/.circleci/config.yml
# I'd love to find docs on this syntax.
references:
  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/project

workflows:
  version: 2
  install_build_deploy:
    jobs:
    - install
    - build_next:
        requires:
        - install
    - build_react:
        requires:
        - install
    - build_org:
        requires:
        - install
    - upload_docs:
        requires:
        - build_react
        - build_next
        - build_org
    - deploy:
        requires:
        - build_react
        - build_next
        - build_org
        filters:
          branches:
            only: master
jobs:
  install:
    docker:
    - image: circleci/node:12
    steps:
    - checkout
    - run:
        name: Pull Submodules
        command: |
          git submodule init
          git submodule update --remote
    - run:
        name: Install
        command: yarn install
    - persist_to_workspace:
        root: ~/project
        paths:
          - "*"
  build_next:
    docker:
    - image: circleci/node:12
    steps:
    - *attach_workspace
    - run:
        name: Build patternfly-next docs
        command: yarn build:next
    - persist_to_workspace:
        root: ~/project
        paths: 
        - patternfly-org-demo/patternfly-next/public/
  build_react:
    docker:
    - image: circleci/node:12
    steps:
    - *attach_workspace
    - run:
        name: Build patternfly-react docs
        command: yarn build:react
    - persist_to_workspace:
        root: ~/project
        paths: 
        - patternfly-org-demo/patternfly-react/packages/patternfly-4/react-docs/public/
  build_org:
    machine:
      image: circleci/classic:latest
    steps:
    - *attach_workspace
    - run:
        name: Build patternfly.org docs
        command: yarn build:org
    - persist_to_workspace:
        root: ~/project
        paths: 
        - patternfly-org-demo/public/
  upload_docs:
    docker:
    - image: circleci/node:10
    steps:
    - *attach_workspace
    - run:
        name: Upload docs
        command: ./circleci/upload-docs.sh
  deploy:
    docker:
    - image: circleci/node:12
    steps:
    - *attach_workspace
    - run:
        name: Avoid Unknown Host for github.com
        command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
    - run:
        name: Deploy to NPM
        command: echo "You wish."
