version: 2

# Adapted from https://github.com/circleci/circleci-docs/blob/master/.circleci/config.yml
# I'd love to find docs on this syntax.
references:
  js_deps_paths: &js_deps_paths
  - node_modules/
  - gatsby-theme-patternfly-org/node_modules/
  - patternfly-org-demo/node_modules/
  - patternfly-org-demo/patternfly-next/node_modules/
  - patternfly-org-demo/patternfly-react/packages/patternfly-4/react-docs/node_modules/
  - patternfly-org-demo/patternfly-react/packages/patternfly-4/react-docs/plugins/gatsby-transformer-react-docgen-typescript/node_modules/
  js_deps_cache_key: &js_deps_cache_key
    js-deps-v{{.Environment.CACHE_VERSION}}-{{checksum "yarn.lock"}}
  build_cache_key: &build_cache_key
    build-cache-v{{.Environment.CACHE_VERSION}}-{{checksum "yarn.lock"}}
  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/project

workflows:
  version: 2
  install_build_deploy:
    jobs:
    - install
    - build_next:
        requires:
        - install
    - build_react:
        requires:
        - install
    - build_org:
        requires:
        - install
    - upload_docs:
        requires:
        - build_react
        - build_next
        - build_org
    - deploy:
        requires:
        - build_react
        - build_next
        - build_org
        filters:
          branches:
            only: master
jobs:
  install:
    docker:
    - image: circleci/node:10
    steps:
    - checkout
    - run:
        name: Pull Submodules
        command: |
          git submodule init
          git submodule update --remote
    - persist_to_workspace:
        root: ~/project
        paths:
          - "*"
    - restore_cache:
        keys:
        - *js_deps_cache_key
    - run:
        name: Conditional install
        command: if [ ! -d node_modules ]; then yarn install --frozen-lockfile; fi
    - save_cache:
        paths: *js_deps_paths
        key: *js_deps_cache_key
  build_next:
    docker:
    - image: circleci/node:10
    steps:
    - *attach_workspace
    - restore_cache:
        keys:
        - *js_deps_cache_key
    - run:
        name: Build patternfly-next docs
        command: yarn build:next
    - persist_to_workspace:
        root: ~/project
        paths: 
        - patternfly-org-demo/patternfly-next/public/
  build_react:
    docker:
    - image: circleci/node:10
    steps:
    - *attach_workspace
    - restore_cache:
        keys:
        - *js_deps_cache_key
    - run:
        name: Build patternfly-react docs
        command: yarn build:react
    - persist_to_workspace:
        root: ~/project
        paths: 
        - patternfly-org-demo/patternfly-react/packages/react-docs/public/
  build_org:
    docker:
    - image: circleci/node:10
    steps:
    - *attach_workspace
    - restore_cache:
        keys:
        - *js_deps_cache_key
    - run:
        name: Build patternfly.org docs
        command: yarn build:org
    - persist_to_workspace:
        root: ~/project
        paths: 
        - patternfly-org-demo/public/
  upload_docs:
    docker:
    - image: circleci/node:10
    steps:
    - *attach_workspace
    - run:
        name: Upload docs
        command: ./circleci/upload-docs.sh
  deploy:
    docker:
    - image: circleci/node:10
    steps:
    - *attach_workspace
    - restore_cache:
        keys:
        - *js_deps_cache_key
    - run:
        name: Avoid Unknown Host for github.com
        command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
    - run:
        name: Deploy to NPM
        command: echo "You wish."
