version: 2

# Adapted from https://github.com/circleci/circleci-docs/blob/master/.circleci/config.yml
# I'd love to find docs on this syntax.
references:
  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/project
workflows:
  version: 2
  install_build_deploy:
    jobs:
    - install
    - build_next:
        requires:
        - install
    - build_react:
        requires:
        - install
    - build_org:
        requires:
        - install
    - upload_docs:
        requires:
        - build_react
        - build_next
        - build_org
    - deploy:
        requires:
        - build_react
        - build_next
        - build_org
        filters:
          branches:
            only: master
jobs:
  install:
    docker:
    - image: circleci/node:12
    steps:
    - checkout
    - run:
        name: Pull Submodules
        command: |
          git submodule init
          git submodule update --remote
    - run:
        name: Install
        command: yarn install
    - persist_to_workspace:
        root: ~/project
        paths:
          - "*"
  build_next:
    docker:
    - image: circleci/node:12
    steps:
    - *attach_workspace
    - run:
        name: Build patternfly-next docs
        command: yarn build:next
    - persist_to_workspace:
        root: ~/project
        paths: 
        - patternfly-org-demo/patternfly-next/public/
  build_react:
    docker:
    - image: circleci/node:12
    steps:
    - *attach_workspace
    - run:
        name: Build patternfly-react docs
        command: yarn build:react
    - persist_to_workspace:
        root: ~/project
        paths: 
        - patternfly-org-demo/patternfly-react/packages/patternfly-4/react-docs/public/
  build_org:
    machine:
      image: circleci/classic:latest
    steps:
    - *attach_workspace
    - run:
        name: Install node@12 (need right version for `yarn`)
        command: |
          set +e             
          curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
          export NVM_DIR="/opt/circleci/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install v12
          nvm alias default v12
          
          # Each step uses the same `$BASH_ENV`, so need to modify it
          echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
          echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV
    - run:
        name: Install yarn
        command: curl -o- -L https://yarnpkg.com/install.sh | bash
    - run:
        name: Build patternfly.org docs
        command: PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH" yarn build:org
    - persist_to_workspace:
        root: ~/project
        paths: 
        - patternfly-org-demo/public/
  upload_docs:
    docker:
    - image: circleci/node:10
    steps:
    - *attach_workspace
    - run:
        name: Upload docs
        command: .circleci/upload-docs.sh
  deploy:
    docker:
    - image: circleci/node:12
    steps:
    - *attach_workspace
    - run:
        name: Avoid Unknown Host for github.com
        command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
    - run:
        name: Deploy to NPM
        command: echo "You wish."
